import express, { Router } from "express";
const router = express.Router();
import controller from "../Controller/user.controller";
import authorization from "../middleware/user.auth";
router.post("/newUser/signUp", controller.signup);
router.post("/user/login", authorization, controller.login);
router.get("/users", controller.getAllUser);
router.get("/user/details", authorization, controller.getUserDetails);
router.delete("/user/delete", authorization, controller.deleteUser);
router.put("/user/update", authorization, controller.updateUser);
router.post("/user/deactivate", authorization, controller.deactivate);
router.post("/user/reactivate", authorization, controller.reactivate);
router.use("*", controller.errs);
export default router;
