import express, { Router } from "express";
const router = express.Router();
import controller from "../Controller/controller";
import auth from "../middleware/auth";
router.post("/newUser/signUp", controller.signup);
router.post("/user/login",auth, controller.login);
router.get("/AllUsers", controller.getAllUser);
router.get("/user/details",auth, controller.getUserDetails);
router.delete("/user/delete", auth, controller.deleteUser);
router.put("/user/update", auth, controller.updateUser);
router.post("/user/deactivate", auth, controller.deactivate);
router.post("/user/reactivate", auth, controller.reactivate);
router.use("*", controller.errs);
export default router;
